# Site settings
title: Central New York Help
description: Help for those seeking it in Rome, Utica, Syracuse, New Hartford, Westmoreland, Lee, Taberg, Whitestown, Sylvan Bech and the surrounding area!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cnyhelp.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: cnyhelp.com
user_description: Help, information and tips for Central New Yorkers
user_title: Central New York Help

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
